"""
Dummy NID data keyed by NIN for testing purposes.
"""

DUMMY_NID_DATA = {
    "८९८-४१४-३७५-३": {
        "nin_loc": "८९८-४१४-३७५-३",
        "first_name": "SUNITA",
        "last_name": "SINTAN LAMA",
        "first_name_loc": "सुनिता",
        "last_name_loc": "सिन्तान लामा",
        "dob": "1990-06-15",
        "dob_loc": "२०४७-०३-०१",
        "gender": "F",
        "perm_state": "3",
        "perm_district": "32",
        "perm_rur_mun": "362",
        "perm_ward": "9",
        "perm_village_tol": "Madanpath",
        "cc_issuing_district": "32",
        "cc_issuing_date": "2009-11-19 00:00:00.0",
        "f_first_name": "JIT",
        "f_last_name": "SINTAN LAMA",
        "m_first_name": "SHARMILA",
        "m_last_name": "SINTAN LAMA",
        "gf_first_name": "KALU",
        "gf_last_name": "SINTAN LAMA",
        "perm_state_loc": "3",
        "perm_district_loc": "32",
        "perm_rur_mun_loc": "362",
        "perm_ward_loc": "९",
        "perm_village_tol_loc": "मदनपथ",
        "cc_number_loc": "३११०२२/६५८४३",
        "cc_issuing_district_loc": "32",
        "cc_issuing_date_loc": "२०६६-०८-०४",
        "f_first_name_loc": "जित",
        "f_last_name_loc": "सिन्तान लामा",
        "m_first_name_loc": "शर्मिला",
        "m_last_name_loc": "सीन्तान लामा",
        "gf_first_name_loc": "कालु",
        "gf_last_name_loc": "सिन्तान लामा",
        "portrait_image": "AAAADGpQICANCocKAAAAFGZ0eXBqcDIg",
    },
    "१२३-४५६-७८९-०": {
        "nin_loc": "१२३-४५६-७८९-०",
        "first_name": "RAM",
        "last_name": "BAHADUR THAPA",
        "first_name_loc": "राम",
        "last_name_loc": "बहादुर थापा",
        "dob": "1985-03-22",
        "dob_loc": "२०४१-१२-०८",
        "gender": "M",
        "perm_state": "1",
        "perm_district": "10",
        "perm_rur_mun": "101",
        "perm_ward": "5",
        "perm_village_tol": "Baluwatar",
        "cc_issuing_district": "10",
        "cc_issuing_date": "2005-07-10 00:00:00.0",
        "f_first_name": "HARI",
        "f_last_name": "BAHADUR THAPA",
        "m_first_name": "SITA",
        "m_last_name": "THAPA",
        "gf_first_name": "BHIM",
        "gf_last_name": "BAHADUR THAPA",
        "perm_state_loc": "1",
        "perm_district_loc": "10",
        "perm_rur_mun_loc": "101",
        "perm_ward_loc": "५",
        "perm_village_tol_loc": "बालुवाटार",
        "cc_number_loc": "१०१०१५/१२३४५",
        "cc_issuing_district_loc": "10",
        "cc_issuing_date_loc": "२०६२-०३-२६",
        "f_first_name_loc": "हरि",
        "f_last_name_loc": "बहादुर थापा",
        "m_first_name_loc": "सीता",
        "m_last_name_loc": "थापा",
        "gf_first_name_loc": "भीम",
        "gf_last_name_loc": "बहादुर थापा",
        "portrait_image": "AAAADGpQICANCocKAAAAFGZ0eXBqcDIg",
    },
    "५५५-१२३-९८७-६": {
        "nin_loc": "५५५-१२३-९८७-६",
        "first_name": "GITA",
        "last_name": "SHARMA",
        "first_name_loc": "गीता",
        "last_name_loc": "शर्मा",
        "dob": "1992-11-05",
        "dob_loc": "२०४९-०७-२०",
        "gender": "F",
        "perm_state": "2",
        "perm_district": "20",
        "perm_rur_mun": "205",
        "perm_ward": "3",
        "perm_village_tol": "Dharan",
        "cc_issuing_district": "20",
        "cc_issuing_date": "2012-04-15 00:00:00.0",
        "f_first_name": "KRISHNA",
        "f_last_name": "SHARMA",
        "m_first_name": "LAXMI",
        "m_last_name": "SHARMA",
        "gf_first_name": "GANESH",
        "gf_last_name": "SHARMA",
        "perm_state_loc": "2",
        "perm_district_loc": "20",
        "perm_rur_mun_loc": "205",
        "perm_ward_loc": "३",
        "perm_village_tol_loc": "धरान",
        "cc_number_loc": "२०२०३५/४५६७८",
        "cc_issuing_district_loc": "20",
        "cc_issuing_date_loc": "२०६९-०१-०३",
        "f_first_name_loc": "कृष्ण",
        "f_last_name_loc": "शर्मा",
        "m_first_name_loc": "लक्ष्मी",
        "m_last_name_loc": "शर्मा",
        "gf_first_name_loc": "गणेश",
        "gf_last_name_loc": "शर्मा",
        "portrait_image": "AAAADGpQICANCocKAAAAFGZ0eXBqcDIg",
    },
    "७७७-८८८-९९९-१": {
        "nin_loc": "७७७-८८८-९९९-१",
        "first_name": "BIKASH",
        "last_name": "GURUNG",
        "first_name_loc": "बिकाश",
        "last_name_loc": "गुरुङ",
        "dob": "1988-01-10",
        "dob_loc": "२०४४-०९-२६",
        "gender": "M",
        "perm_state": "4",
        "perm_district": "40",
        "perm_rur_mun": "410",
        "perm_ward": "7",
        "perm_village_tol": "Pokhara",
        "cc_issuing_district": "40",
        "cc_issuing_date": "2008-05-20 00:00:00.0",
        "f_first_name": "DHAN",
        "f_last_name": "GURUNG",
        "m_first_name": "MAYA",
        "m_last_name": "GURUNG",
        "gf_first_name": "MAN",
        "gf_last_name": "GURUNG",
        "perm_state_loc": "4",
        "perm_district_loc": "40",
        "perm_rur_mun_loc": "410",
        "perm_ward_loc": "७",
        "perm_village_tol_loc": "पोखरा",
        "cc_number_loc": "४०१०७०/७८९१२",
        "cc_issuing_district_loc": "40",
        "cc_issuing_date_loc": "२०६५-०२-०७",
        "f_first_name_loc": "धन",
        "f_last_name_loc": "गुरुङ",
        "m_first_name_loc": "माया",
        "m_last_name_loc": "गुरुङ",
        "gf_first_name_loc": "मन",
        "gf_last_name_loc": "गुरुङ",
        "portrait_image": "AAAADGpQICANCocKAAAAFGZ0eXBqcDIg",
    },
    "३३३-२२२-१११-४": {
        "nin_loc": "३३३-२२२-१११-४",
        "first_name": "ANITA",
        "last_name": "ADHIKARI",
        "first_name_loc": "अनिता",
        "last_name_loc": "अधिकारी",
        "dob": "1995-08-30",
        "dob_loc": "२०५२-०५-१४",
        "gender": "F",
        "perm_state": "5",
        "perm_district": "50",
        "perm_rur_mun": "502",
        "perm_ward": "2",
        "perm_village_tol": "Butwal",
        "cc_issuing_district": "50",
        "cc_issuing_date": "2015-09-12 00:00:00.0",
        "f_first_name": "BISHNU",
        "f_last_name": "ADHIKARI",
        "m_first_name": "DURGA",
        "m_last_name": "ADHIKARI",
        "gf_first_name": "TULSI",
        "gf_last_name": "ADHIKARI",
        "perm_state_loc": "5",
        "perm_district_loc": "50",
        "perm_rur_mun_loc": "502",
        "perm_ward_loc": "२",
        "perm_village_tol_loc": "बुटवल",
        "cc_number_loc": "५०५०२०/९८७६५",
        "cc_issuing_district_loc": "50",
        "cc_issuing_date_loc": "२०७२-०५-२७",
        "f_first_name_loc": "बिष्णु",
        "f_last_name_loc": "अधिकारी",
        "m_first_name_loc": "दुर्गा",
        "m_last_name_loc": "अधिकारी",
        "gf_first_name_loc": "तुलसी",
        "gf_last_name_loc": "अधिकारी",
        "portrait_image": "AAAADGpQICANCocKAAAAFGZ0eXBqcDIg",
    },
    "६६६-५५५-४४४-२": {
        "nin_loc": "६६६-५५५-४४४-२",
        "first_name": "SANJAY",
        "last_name": "MAHARJAN",
        "first_name_loc": "सन्जय",
        "last_name_loc": "महर्जन",
        "dob": "1982-12-25",
        "dob_loc": "२०३९-०९-१०",
        "gender": "M",
        "perm_state": "3",
        "perm_district": "27",
        "perm_rur_mun": "275",
        "perm_ward": "12",
        "perm_village_tol": "Lalitpur",
        "cc_issuing_district": "27",
        "cc_issuing_date": "2003-02-14 00:00:00.0",
        "f_first_name": "NARAYAN",
        "f_last_name": "MAHARJAN",
        "m_first_name": "KAMALA",
        "m_last_name": "MAHARJAN",
        "gf_first_name": "RATNA",
        "gf_last_name": "MAHARJAN",
        "perm_state_loc": "3",
        "perm_district_loc": "27",
        "perm_rur_mun_loc": "275",
        "perm_ward_loc": "१२",
        "perm_village_tol_loc": "ललितपुर",
        "cc_number_loc": "२७२७५१/३४५६७",
        "cc_issuing_district_loc": "27",
        "cc_issuing_date_loc": "२०५९-११-०२",
        "f_first_name_loc": "नारायण",
        "f_last_name_loc": "महर्जन",
        "m_first_name_loc": "कमला",
        "m_last_name_loc": "महर्जन",
        "gf_first_name_loc": "रत्न",
        "gf_last_name_loc": "महर्जन",
        "portrait_image": "AAAADGpQICANCocKAAAAFGZ0eXBqcDIg",
    },
    "१११-२२२-३३३-५": {
        "nin_loc": "१११-२२२-३३३-५",
        "first_name": "PRAMILA",
        "last_name": "TAMANG",
        "first_name_loc": "प्रमिला",
        "last_name_loc": "तामाङ",
        "dob": "1998-04-18",
        "dob_loc": "२०५५-०१-०५",
        "gender": "F",
        "perm_state": "3",
        "perm_district": "26",
        "perm_rur_mun": "263",
        "perm_ward": "6",
        "perm_village_tol": "Bhaktapur",
        "cc_issuing_district": "26",
        "cc_issuing_date": "2018-01-20 00:00:00.0",
        "f_first_name": "BUDDHI",
        "f_last_name": "TAMANG",
        "m_first_name": "DEVI",
        "m_last_name": "TAMANG",
        "gf_first_name": "PURNA",
        "gf_last_name": "TAMANG",
        "perm_state_loc": "3",
        "perm_district_loc": "26",
        "perm_rur_mun_loc": "263",
        "perm_ward_loc": "६",
        "perm_village_tol_loc": "भक्तपुर",
        "cc_number_loc": "२६२६३६/५४३२१",
        "cc_issuing_district_loc": "26",
        "cc_issuing_date_loc": "२०७४-१०-०६",
        "f_first_name_loc": "बुद्धि",
        "f_last_name_loc": "तामाङ",
        "m_first_name_loc": "देवी",
        "m_last_name_loc": "तामाङ",
        "gf_first_name_loc": "पूर्ण",
        "gf_last_name_loc": "तामाङ",
        "portrait_image": "AAAADGpQICANCocKAAAAFGZ0eXBqcDIg",
    },
    "४४४-३३३-२२२-७": {
        "nin_loc": "४४४-३३३-२२२-७",
        "first_name": "DEEPAK",
        "last_name": "KC",
        "first_name_loc": "दीपक",
        "last_name_loc": "केसी",
        "dob": "1975-07-07",
        "dob_loc": "२०३२-०३-२३",
        "gender": "M",
        "perm_state": "6",
        "perm_district": "60",
        "perm_rur_mun": "601",
        "perm_ward": "1",
        "perm_village_tol": "Nepalgunj",
        "cc_issuing_district": "60",
        "cc_issuing_date": "1996-03-05 00:00:00.0",
        "f_first_name": "GOPAL",
        "f_last_name": "KC",
        "m_first_name": "SARASWATI",
        "m_last_name": "KC",
        "gf_first_name": "PADAM",
        "gf_last_name": "KC",
        "perm_state_loc": "6",
        "perm_district_loc": "60",
        "perm_rur_mun_loc": "601",
        "perm_ward_loc": "१",
        "perm_village_tol_loc": "नेपालगञ्ज",
        "cc_number_loc": "६०६०१०/११२२३",
        "cc_issuing_district_loc": "60",
        "cc_issuing_date_loc": "२०५२-११-२२",
        "f_first_name_loc": "गोपाल",
        "f_last_name_loc": "केसी",
        "m_first_name_loc": "सरस्वती",
        "m_last_name_loc": "केसी",
        "gf_first_name_loc": "पदम",
        "gf_last_name_loc": "केसी",
        "portrait_image": "AAAADGpQICANCocKAAAAFGZ0eXBqcDIg",
    },
    "९९९-८८८-७७७-८": {
        "nin_loc": "९९९-८८८-७७७-८",
        "first_name": "SABINA",
        "last_name": "RAI",
        "first_name_loc": "सबिना",
        "last_name_loc": "राई",
        "dob": "2000-02-14",
        "dob_loc": "२०५६-११-०२",
        "gender": "F",
        "perm_state": "1",
        "perm_district": "14",
        "perm_rur_mun": "140",
        "perm_ward": "8",
        "perm_village_tol": "Biratnagar",
        "cc_issuing_district": "14",
        "cc_issuing_date": "2020-06-01 00:00:00.0",
        "f_first_name": "KUMAR",
        "f_last_name": "RAI",
        "m_first_name": "BIMALA",
        "m_last_name": "RAI",
        "gf_first_name": "DAL",
        "gf_last_name": "RAI",
        "perm_state_loc": "1",
        "perm_district_loc": "14",
        "perm_rur_mun_loc": "140",
        "perm_ward_loc": "८",
        "perm_village_tol_loc": "बिराटनगर",
        "cc_number_loc": "१४१४०८/६७८९०",
        "cc_issuing_district_loc": "14",
        "cc_issuing_date_loc": "२०७७-०२-१९",
        "f_first_name_loc": "कुमार",
        "f_last_name_loc": "राई",
        "m_first_name_loc": "बिमला",
        "m_last_name_loc": "राई",
        "gf_first_name_loc": "दल",
        "gf_last_name_loc": "राई",
        "portrait_image": "AAAADGpQICANCocKAAAAFGZ0eXBqcDIg",
    },
    "२२२-१११-०००-९": {
        "nin_loc": "२२२-१११-०००-९",
        "first_name": "RAJESH",
        "last_name": "SHRESTHA",
        "first_name_loc": "राजेश",
        "last_name_loc": "श्रेष्ठ",
        "dob": "1979-09-20",
        "dob_loc": "२०३६-०६-०४",
        "gender": "M",
        "perm_state": "3",
        "perm_district": "25",
        "perm_rur_mun": "250",
        "perm_ward": "15",
        "perm_village_tol": "Kathmandu",
        "cc_issuing_district": "25",
        "cc_issuing_date": "2000-08-10 00:00:00.0",
        "f_first_name": "SHYAM",
        "f_last_name": "SHRESTHA",
        "m_first_name": "RADHA",
        "m_last_name": "SHRESTHA",
        "gf_first_name": "MOHAN",
        "gf_last_name": "SHRESTHA",
        "perm_state_loc": "3",
        "perm_district_loc": "25",
        "perm_rur_mun_loc": "250",
        "perm_ward_loc": "१५",
        "perm_village_tol_loc": "काठमाडौं",
        "cc_number_loc": "२५२५१५/२३४५६",
        "cc_issuing_district_loc": "25",
        "cc_issuing_date_loc": "२०५७-०४-२६",
        "f_first_name_loc": "श्याम",
        "f_last_name_loc": "श्रेष्ठ",
        "m_first_name_loc": "राधा",
        "m_last_name_loc": "श्रेष्ठ",
        "gf_first_name_loc": "मोहन",
        "gf_last_name_loc": "श्रेष्ठ",
        "portrait_image": "AAAADGpQICANCocKAAAAFGZ0eXBqcDIg",
    },
}
